### PR TITLE
Restore and fix remote trigger

### PR DESCRIPTION
**Pull request by beckyconning**

### CODE REVIEW

**Comment by beckyconning** [comment]
Tested using the documented instructions on Windows, Ubuntu and Mac.

**Comment by beckyconning** [comment]
@anko @spajak ready to go? : )

**Comment by spajak** [comment]
I'm against as long as we have no way to kill the process. I could agree for remote trigger in command line mode (not in server mode)

**Comment by beckyconning** [comment]
Sounds strong to me! : ) Shall I remove the server mode support?

**Comment by beckyconning** [comment]
@spajak @anko ready to go? : )

**Comment by beckyconning** [comment]
Thanks so much for reviewing and merging this PR. It would be very useful to me if you could run a new release including these changes. Thanks.

**Comment by beckyconning** [comment]
Hi I would be deeply grateful for a release including these changes. The current release does not include them.

**Pull request merged**
